# Generated by Django 5.0.6 on 2024-07-14 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_description_item_region_remove_item_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Discord',
            new_name='Phil_Health_Number',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Facebook',
            new_name='SSN',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Instagram',
            new_name='TIN_ID',
        ),
    ]
